Wehelp Stage2 Week1 Tasks
54Laichu/taipei-day-trip pull request #2
Opened 2024-05-28 10:26 UTC by 54Laichu

賴益楚

- GET Attractions API
http://54.157.160.232:8000/api/attractions?page=1
http://54.157.160.232:8000/api/attractions?page=0&keyword=劍潭
http://54.157.160.232:8000/api/attractions?page=0&keyword=北

- GET Attraction API
http://54.157.160.232:8000/api/attraction/10

- GET MRTs API
http://54.157.160.232:8000/api/mrts

2024-05-28 21:45 UTC, cwpeng requested changes
1. nextPage of the last page should be null, for example, http://54.157.160.232:8000/api/attractions?page=1&keyword=%E5%8C%97
2. response format of http://54.157.160.232:8000/api/mrts is incorrect.

2024-05-29 02:44 UTC, 54Laichu commented on app.py
> +        mrt_list = [mrt[0] for mrt in mrt_tuple if mrt[0] is not None]
已修正資料格式的錯誤

2024-05-29 02:45 UTC, 54Laichu commented on app.py
> +        next_page = page + 1 if len(attractions) == limit and page + 1 < total_pages else None
已修正錯誤的頁碼規則

2024-05-29 19:11 UTC, cwpeng approved these changes
OK. Done.

2024-05-30 00:34 UTC, merged