Wehelp Stage2 Week2
54Laichu/taipei-day-trip pull request #3
Opened 2024-06-05 15:33 UTC by 54Laichu

賴益楚
http://54.157.160.232:8000/

2024-06-05 21:11 UTC, cwpeng requested changes
Take care of details: text size, color, border styling.
![54 157 160 232_8000_](https://github.com/54Laichu/taipei-day-trip/assets/6104683/867877d1-2b32-4f80-b2be-bdcb72bc96f9)

2024-06-06 01:54 UTC, 54Laichu commented
Bug fixed, thanks for reminding :)
![截圖 2024-06-06 上午9 53 32](https://github.com/54Laichu/taipei-day-trip/assets/160101542/c24d77ec-d3a6-49eb-9a2c-e680d7086e4e)

2024-06-06 07:11 UTC, cwpeng requested changes
If we search 北, there should be only 2 pages data.

2024-06-06 11:27 UTC, 54Laichu commented
Bug: 先前的 loadNextPage function 無法中斷，導致如果在載入的過程中進行其他 query ，GET request會疊加上去。
```
INFO:     127.0.0.1:63496 - "GET /api/mrts HTTP/1.1" 200 OK
INFO:     127.0.0.1:63497 - "GET /api/attractions?page=0& HTTP/1.1" 200 OK
INFO:     127.0.0.1:63571 - "GET /api/attractions?page=0&keyword=%E5%8C%97 HTTP/1.1" 200 OK
INFO:     127.0.0.1:63571 - "GET /api/attractions?page=1& HTTP/1.1" 200 OK
INFO:     127.0.0.1:63589 - "GET /api/attractions?page=1&keyword=%E5%8C%97 HTTP/1.1" 200 OK
INFO:     127.0.0.1:63589 - "GET /api/attractions?page=2& HTTP/1.1" 200 OK
...
```

在參考 youtube 影片 https://www.youtube.com/watch?v=2IbRtjez6ag&ab_channel=WebDevSimplified 及詢問GPT後更新做法：
1. 以 `IntersectionObserver` object 觀察 `.bottom` 是否出現在畫面。
2. 出現的話就繼續發送 GET request
3. 如果中途有其他 `click` `search` or `mrt` event ，則 `resetLoading` 中斷原本在觀察的任務

2024-06-06 11:28 UTC, 54Laichu commented on static/js/loadAttractions.js
> +function resetLoading() {
如果中途有其他 `click` `search` or `mrt` event ，則 `resetLoading()` 中斷原本在觀察的任務

2024-06-06 11:37 UTC, 54Laichu commented on static/js/search.js
> +      resetLoading();
中斷可能原本在觀察的任務

2024-06-06 11:38 UTC, 54Laichu commented on static/js/scrollMRT.js
> +              resetLoading();
中斷可能原本在觀察的任務

2024-06-06 11:40 UTC, 54Laichu commented on static/js/loadAttractions.js
> +function resetLoading() {
如果中途有其他 `click` `search` or `mrt` event ，則 `resetLoading()` 中斷原本在觀察的任務

2024-06-06 13:00 UTC, cwpeng approved these changes
OK. Done.

2024-06-06 13:49 UTC, merged