Attraction.html (Wehelp_s2_wk3)
54Laichu/taipei-day-trip pull request #4
Opened 2024-06-12 16:00 UTC by 54Laichu

賴益楚
http://54.157.160.232:8000/
http://54.157.160.232:8000/attraction/2

* 註：今天不小心把 local branch 搞砸了，所以重捏了一顆大 commit 。而且在 EC2 上面 pull 的時候還衝突，花了一個晚上研究如何用內建編輯器排解問題。

2024-06-12 19:13 UTC, cwpeng requested changes
Take attention on details: spacing, padding, border.
![54 157 160 232_8000_attraction_2](https://github.com/54Laichu/taipei-day-trip/assets/6104683/53d71128-b48f-4869-8b44-2b2a914b7a0a)

2024-06-13 03:27 UTC, 54Laichu commented on static/attraction.html
> +                <div><input type="date" placeholder="MM-DD-YYYY"></div>
修正日期格式

2024-06-13 03:28 UTC, 54Laichu commented on static/css/index.css
> +  .show-attraction-container {
修正行動裝置版面

2024-06-13 03:45 UTC, 54Laichu commented on static/attraction.html
> +                <div><input type="date" placeholder="YYYY-MM-DD"></div>
修正日期格式

2024-06-13 04:02 UTC, 54Laichu commented on static/css/index.css
> +  .show-attraction-container {
修正行動裝置版面

2024-06-13 04:11 UTC, 54Laichu commented on static/css/index.css
> +  .show-attraction-container {
<img width="200" alt="截圖 2024-06-13 中午12 10 47" src="https://github.com/54Laichu/taipei-day-trip/assets/160101542/5f67ef1b-02ae-4bbd-bc6e-e9594323a2e9">

2024-06-13 13:15 UTC, cwpeng requested changes
Take attention on border and padding of data input element.

2024-06-13 15:43 UTC, 54Laichu commented on static/js/attraction.js
> +    inputField.showPicker();
use showPicker() API so user can click the whole div to pop up date selector.

2024-06-13 15:44 UTC, 54Laichu commented on static/css/index.css
> +  width: 193px;
![Capture-2024-06-13-234055](https://github.com/54Laichu/taipei-day-trip/assets/160101542/671ef27e-e780-4fb9-9937-ef620517c291)

2024-06-13 16:33 UTC, cwpeng approved these changes
OK. Done.

2024-06-14 00:02 UTC, merged