Wehelp Stage2 Week4 Tasks
54Laichu/taipei-day-trip pull request #5
Opened 2024-06-20 06:57 UTC by 54Laichu

賴益楚
http://54.157.160.232:8000
http://54.157.160.232:8000/10

2024-06-20 16:59 UTC, cwpeng requested changes
Reload page after successful signing in.

2024-06-21 03:02 UTC, 54Laichu commented on static/js/userAuth.js
> -          signInButton.innerHTML = '<p>登出系統</p>';
if user login successfully, reload current page

2024-06-21 03:03 UTC, 54Laichu commented on static/js/userAuth.js
> +            window.location.reload();
if user login successfully, reload current page

2024-06-21 03:04 UTC, 54Laichu commented on static/js/userAuth.js
> +          }, 1000);
if user login successfully, reload current page

2024-06-21 03:34 UTC, cwpeng approved these changes
OK. Done.

2024-06-21 03:37 UTC, merged